# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_like', to='secrets.Secret')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='secret_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
